Mise à jour environnement docker

diff --git a/.bash_enter.d/95-init b/.bash_enter.d/95-init
--- a/.bash_enter.d/95-init
+++ b/.bash_enter.d/95-init
@@ -1,18 +1,10 @@
 #!/usr/bin/env bash
 
-if [ -f "./init/init.sh" ] && [ -f ./init/.should-initialize ]; then
-  read -p "Project is not initialized. Do you want to initialize it ? [y/N]: " -n 1 -r
-  echo
-  if [[ $REPLY =~ ^[Yy]$ ]]
-  then
-      echo "Running initialization script: ./init/init.sh"
-      ./init/init.sh
-      if [ $? -eq 0 ]; then
-        echo "Initialization succeded"
-      else
-        echo "Initialization failed"
-      fi
+if [ -f "./.init/init.sh" ] && [ -f ./.init/.should-initialize ]; then
+  echo "Running initialization script: ./.init/init.sh"
+  if ! ./.init/init.sh; then
+    echo "Initialization failed"
   else
-      echo "Initialization skipped"
+    echo "Initialization succeded"
   fi
 fi
